POST http://localhost:3030/reports
Content-Type: application/json

{
    "make": "honda",
    "model": "sivic",
    "year": 2000,
    "mileage": 50000,
    "lng": 45,
    "lat": 45,
    "price": 30000
}

### Approve an existing report
PATCH http://localhost:3030/reports/7
Content-Type: application/json

{
    "approved": true
}


### Get an estimate fo an exiting vehicle tìm theo điều kiện 

GET http://localhost:3030/reports?make=honda&model=sivic&lng=45&lat=45&mileage=50000&year=2000